### ISSUE TITLE
An event stay on lockscreen even after remove the app

### ISSUE THREAD

**Issue by khalangy** [dgudim/Scheduler#3]
Hi,
Thanks for this app. 
I have a bug with it, an event stay on lockscreen even after removing the app or remove the event in calendar. 

I am on CalyxOS 4.3.1 Android 13. 
Phone : pixel 4a

Thanks for helping
Best regards

**Comment by dgudim** [comment]
Hello, thanks for reporting. The event stays after removing the app because it draws on top of your background and when you remove the app the background just stays, you can manually set your background back. And for the calendar event, the app refreshes the calendars every 10 minutes so it's probably that. If you have any questions, feel free to ask.

**Comment by khalangy** [comment]
> Hello, thanks for reporting. The event stays after removing the app because it draws on top of your background and when you remove the app the background just stays, you can manually set your background back. And for the calendar event, the app refreshes the calendars every 10 minutes so it's probably that. If you have any questions, feel free to ask.

Thanks for helping, setting the background works like a charm 😁

**Comment by khalangy** [comment]
Problem solved

**Comment by khalangy** [comment]
Problem solved
